//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "organization")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub email: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub phone: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub website: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub industry: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub address: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub city: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub state: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub postal_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub country_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub timezone: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub currency: Option<String>,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::organization_contact::Entity")]
    OrganizationContact,
}

impl Related<super::organization_contact::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrganizationContact.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
