//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

pub use super::contact::Entity as Contact;
pub use super::organization::Entity as Organization;
pub use super::organization_contact::Entity as OrganizationContact;
